### PR TITLE
Upgrade PHP to 7.4

### PR DESCRIPTION
**Pull request by davidbarratt**

### CODE REVIEW

**Comment by d0niek** [comment]
What are we waiting for? :-)

**Comment by davidbarratt** [comment]
Nothing really I just hadn't tested it. Would you mind testing it and making sure everything works? :)

**Comment by d0niek** [comment]
Try to find free time and I will do it ;-)

**Comment by d0niek** [comment]
Hi @davidbarratt !
I have just update my Dockerfiles and images base on this PR and it looks like everything is working ;-)

**Pull request merged**
