### PR TITLE
include openssh-client

### PR DESCRIPTION
**Pull request by enko**
This is needed if you want to mirror repositories from phabricator to another host via ssh

### CODE REVIEW

**Comment by davidbarratt** [comment]
Can you also add it to `Dockerfile.aphlict` ? It would also be nice to have a comment (preferablly with a URL as a source like the one a few lines above) with why it's needed?

**Comment by enko** [comment]
@davidbarratt Thanks for the review! I added a link to the dependency page where it states why it is needed. I also expanded the commit message a bit, should I put that also in a comment inside the `Dockerfile`?

**Comment by davidbarratt** [comment]
yeah I think that would be wise so I don't question it in the future. :) Also if you can rebase your branch I've added a little test action to ensure it still at least builds. :)

**Comment by enko** [comment]
@davidbarratt Done

**Comment by davidbarratt** [comment]
This looks fantastic! would you mind creating another branch off of `stable` and cherry picking your changes and opening a PR to `stable` ?

**Pull request merged**
